### PR TITLE
Detect device replugged

### PR DESCRIPTION
**Pull request by hrchu**
Detect device unplugged and plugged events and ensure executions will not fail
silently due to replugged events. This may happen on a long run.

### CODE REVIEW

**Comment by rosjat** [comment]
is it for usb devices?

**Comment by hrchu** [comment]
It is for any device as long as udev does not reserve the inode for devices have been seem. In my case it's a tape library. 

If the fiber channel of a tape library replugged, I always get out-of-date status of the tape library without any error message.

Note that I tested a usb mass storage device on my box and have the same issue.

**Comment by rosjat** [comment]
sorry for the late reply i was away a few days so no internet!
I will merge the request now, we never had a long running process use in mind i get s owe never really came to experience this issue. As fas as i see it looks sane and it might help others who intent to use it for more stuff then testing!

**Comment by hrchu** [comment]
Yeah we are trying to do some rocket science based on your project. Many thanks!

**Comment by rosjat** [comment]
Rocket science is cool :) but I guess it's not to much rockets involved :)

hrchu <notifications@github.com> schrieb am Do., 4. Apr. 2019, 09:43:

**Pull request merged**
